import { load } from 'cheerio'

const response = await (await fetch('https://www.cloudflarestatus.com')).text()
const $ = load(response)
const locations = Object.fromEntries(
    $('.component-container:not(:first-child) > .child-components-container .name')
        .toArray()
        .map((el) => $(el).text().trim())
        .map((x) => {
            const match = x.match(/^(.*) - \((.*)\)/)
            if (match) return [match[2], match[1]]
            return undefined
        })
        .filter((x) => x !== undefined),
)

console.log(
    `// This file is auto-generated by scripts/cloudflare-colo-update.ts
// run "bun colo > ./content/site/colo.ts" to update
export const CloudflareServerLocations = ` + JSON.stringify(locations, null, 2) + ` as const`,
)
